### ISSUE TITLE
2 "Tetravex" enteries on FlatHub ! Please fix

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.gnome.Tetravex#2]
Hi. I detect that there are, currently, 2 "Tetravex" on FlatHub ! Is this correct, or a bug ? I suspect it as a bug.

https://www.flathub.org/apps/details/org.gnome.Tetravex
&
https://www.flathub.org/apps/details/org.gnome.tetravex

**Comment by TingPing** [comment]
An admin will have to delete the extra entry (cc @alexlarsson)
